### ISSUE TITLE
Timezones but they work properly

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Lonabot#10]
```
<adam>   lonabot just saves the tz offset at the moment you do /tz
<adam>   @lonami please to fix
<lonami> > unironically using iso-date formats
```

**Comment by Sharparam** [comment]
After #16 is merged, this can maybe be considered fixed? The only thing I can see now that is not "fixed" is /remind with a relative time.

If you `/remind 3d` and on the third day it transitions into winter time for example, it will come up an hour short. But this feels much more annoying to fix compared to when the remind command is given a fixed date.
