### ISSUE TITLE
Reminders fail if the message they should reply to was deleted

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Lonabot#17]

**Comment by Lonami** [comment]
Can no longer reproduce?

**Comment by Sharparam** [comment]
It seems to "work" as far as I can see: 
![image](https://user-images.githubusercontent.com/551094/135722314-2747d178-1c5c-4fed-87f5-9d110c83b825.png)

The reminder still goes off and it replies properly. I think we can close this?
