### ISSUE TITLE
Handle alternative offset formats

### ISSUE THREAD

**Issue by Sharparam** [LonamiWebs/Lonabot#33]
Currently, you can specify an offset when setting a reminder, e.g.:

```
/remind 2023-02-14T20:00:00+01:00 Cry in bed because you're alone
```

However, the other common methods of specifying an offset (`+01` for just hours, or `+0100` for hours+minutes without a separator) do not work, because Python's "ISO" datetime parser is not ISO compliant.

Perhaps this should be detected and fixed manually within the parsing code in Lonabot? (Like we currently do for converting "Z" and "z" to "+00:00" because Python™.)

I'm prepared to work on this fix but not sure when I will have the time.

**Comment by 9ary** [comment]
Considering https://github.com/python/cpython/issues/80010 is on its way for python 3.11, I don't think we need to bother fixing this ourselves.
