### ISSUE TITLE
Calendar bot

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Lonabot#4]
But instead of reminding you in 5 minutes it reminds you yearly. With fancy inline buttons. cc @Faith001:
> can somebody make that slick inline button calendar bot already

**Comment by expectocode** [comment]
Is there any reason to keep this open if nobody (including OP) can implement it?

**Comment by Lonami** [comment]
Anyone (including OP) *can* implement it. It's simply a very, very low priority enhancement issue.

**Comment by Lonami** [comment]
💪
